const Colors = Object.freeze({
  HOME_BG_COLOR: 'white',
  HOME_VECT_COLOR: '#4B4B4B',
  HOME_NAVBAR_COLOR: 'white',
  HOME_NAVBAR_TINT: '#FE9179',
  SLEEP_BG_COLOR: '#152B4B',
  SLEEP_VECT_COLOR: '#CEE2FF',
  SLEEP_NAVBAR_COLOR: '#274067',
  SLEEP_NAVBAR_TINT: '#FFD953',
  MEDITATION_BG_COLOR: 'white',
  MEDITATION_VECT_COLOR: '#4B4B4B',
  MEDITATION_NAVBAR_COLOR: 'white',
  MEDITATION_NAVBAR_TINT: '#FE9179',
});

export {Colors};
